---
kind: pipeline
name: default

steps:
- name: container
  image: plugins/docker
  settings:
    repo: cr.blackieops.com/alexblackie.com
    username: deploy
    password:
      from_secret: docker_password
    registry: cr.blackieops.com
    tags: ${DRONE_COMMIT_SHA:0:8}
  when:
    branch:
    - master
