---
webroot: /www
trusted_proxies: []
headers:
- name: Content-Security-Policy
  value: "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://plausible.io; connect-src https://plausible.io"
- name: X-Content-Type-Options
  value: nosniff
- name: X-XSS-Protection
  value: "1; mode=block"
- name: X-Download-Options
  value: noopen
- name: X-Permitted-Cross-Domain-Policies
  value: none
- name: X-Frame-Options
  value: DENY
- name: Strict-Transport-Security
  value: max-age=7776000
