FROM alpine:3.14

ENV CHROMA_VERSION=0.9.2 \
	SHOREMAN_REF=f39ef22251c25c8df153202d26a6b0dde76ce489

RUN apk add --no-cache nginx coreutils bash make entr curl && \
	curl -SsLo /usr/bin/shoreman https://github.com/chrismytton/shoreman/raw/${SHOREMAN_REF}/shoreman.sh && chmod 755 /usr/bin/shoreman

RUN echo "daemon off; \
events {} \
http { \
	include mime.types; \
	server { \
		listen 3000;\
		root /data/_build; \
	} \
}" > /etc/nginx/nginx.conf

RUN echo -e "web: nginx\nbuild: find . -type f | entr -cr make" > /usr/lib/Procfile

VOLUME /data
WORKDIR /data

CMD ["/usr/bin/shoreman", "/usr/lib/Procfile"]
