# fly.toml app configuration file generated for watashi-production on 2024-06-09T10:59:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'watashi-production'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
