---
name: Deploy (Production)

'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.150.0'

      - name: Build
        run: hugo --minify

      - name: Deploy to Worktree Sites
        uses: worktree/deploy-site@v2
        with:
          source: ./public
          site_id: 5wuRfsALW5tgsD86GQDnNu
          public_key: ${{ secrets.WT_CLOUD_PUBLIC_KEY }}
          secret_key: ${{ secrets.WT_CLOUD_SECRET_KEY }}
