---
name: Deploy (Production)

'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.0'

      - name: Build
        run: hugo --minify

      - name: Deploy to Worktree Sites
        uses: worktree/deploy-site@68cc46e0d65d06de326b187f6e314795f58623e2
        with:
          source: public
          site_id: 5PfbGnqkCTUrkPghHh8pTN
          deploy_token: ${{ secrets.SITES_DEPLOY_TOKEN }}
