---

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: container
    image: woodpeckerci/plugin-docker-buildx:5.0.0
    settings:
      registry: worktree.ca
      repo: worktree.ca/alex/watashi
      platforms: linux/amd64
      auto_tag: true
      tag: ${CI_COMMIT_SHA}
      username: alex
      password:
        from_secret: docker_password
