---
name: Canary Deployment
on:
  push:
    branches:
    - deploy/canary
jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      WATASHI_ENV: canary
    steps:
    - uses: actions/checkout@v2

    - name: Compile
      run: make clean all

    - name: Publish Artifacts
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: _build/
        container_name: '$web'
        connection_string: ${{ secrets.CanaryConnectionString }}
        sync: true
        # Set cache hints to extremely low value to avoid a lot of caching, as
        # it's a canary deployment.
        extra_args: '--content-cache-control=public,max-age=1'
