---
name: Deploy
on:
  push:
    branches:
    - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        - uses: superfly/flyctl-actions/setup-flyctl@67ddda2a87628f1aff28a54b8a708879ec62c80f
        - run: flyctl deploy --remote-only
