---
name: Deploy (Production)

'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.0'

      - name: Build
        run: hugo --minify

      - uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          source_dir: public
          container_name: '$web'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          overwrite: 'true'
