---
name: Test Suite
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.1.1"
          elixir-version: "1.14.5"

      - run: mix format --check-formatted
      - run: mix deps.get
      - run: mix test
